# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['entry_point_gui.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/fa_md_pdf/assets/default.css', 'fa_md_pdf/assets'),
    ],
    hiddenimports=[
        'fa_md_pdf',
        'fa_md_pdf.cli',
        'fa_md_pdf.gui',
        'fa_md_pdf.converter',
        'fa_md_pdf.html_builder',
        'fa_md_pdf.defaults',
        'fa_md_pdf.docx_builder',
        'fa_md_pdf.rtl_wrapper',
        'docx',
        'docx.image.image',
        'pygments',
        'pygments.lexers',
        'pygments.formatters',
        'markdown_it',
        'markdown_it.main',
        'markdown_it.rules_core',
        'markdown_it.rules_block',
        'markdown_it.rules_inline',
        'markdown_it.common',
        'markdown_it.helpers',
        'markdown_it.presets',
        'markdown_it.presets.default',
        'markdown_it.presets.commonmark',
        'markdown_it.presets.zero',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='fa-md-pdf-gui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
