blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/hamid-morsali-786/MdPersia/discussions
    about: Ask questions, share documents, or discuss ideas with the community.
